import { EventItem, Ticket, Vehicle, UserProfile, CheckInLog, DashboardStats, MercadoPagoConfig, NotificationItem } from '../types';

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-1',
    slug: 'encontro-px-custom',
    name: 'Encontro PX Custom',
    tagline: 'O maior encontro automotivo da região',
    description: 'O Encontro PX Custom é mais que um evento, é um ponto de encontro para apaixonados por carros, cultura e liberdade. Prepare seu veículo, reúna a galera e venha viver essa experiência com a gente!',
    date: '15 de Novembro de 2025',
    dateBadge: '15 NOV',
    time: 'Das 08:00 às 22:00',
    location: 'Parque de Exposições - Manhuaçu/MG',
    city: 'Manhuaçu',
    state: 'MG',
    status: 'EM_BREVE',
    bannerImage: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80',
    ],
    features: {
      cars: true,
      motos: true,
      audio: true,
      food: true,
    },
    ticketBatches: [
      {
        id: 'batch-1',
        name: 'Pista',
        description: 'Acesso ao evento, área principal e estandes.',
        price: 40.0,
        totalQuantity: 600,
        soldQuantity: 410,
        available: true,
        batchNumber: 1,
      },
      {
        id: 'batch-2',
        name: 'Camarote',
        description: 'Área exclusiva, open bar e vista privilegiada para as pistas.',
        price: 80.0,
        totalQuantity: 250,
        soldQuantity: 212,
        available: true,
        batchNumber: 1,
      },
      {
        id: 'batch-3',
        name: 'VIP',
        description: 'Acesso total, backstage, estacionamento VIP e benefícios exclusivos.',
        price: 120.0,
        totalQuantity: 150,
        soldQuantity: 120,
        available: true,
        batchNumber: 1,
      },
    ],
    latitude: -20.2582,
    longitude: -42.0336,
  },
  {
    id: 'evt-2',
    slug: 'festival-da-familia',
    name: 'Festival da Família',
    tagline: 'Música, cultura e encontro de antigos e customizados',
    description: 'Um dia inesquecível reunindo famílias e apaixonados pelo universo automotivo. Shows ao vivo, praça gastronômica premium, espaço kids e exposição de relíquias.',
    date: '12 de Dezembro de 2025',
    dateBadge: '12 DEZ',
    time: 'Das 10:00 às 20:00',
    location: 'Parque de Exposições - Manhuaçu/MG',
    city: 'Manhuaçu',
    state: 'MG',
    status: 'EM_ANDAMENTO',
    bannerImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    ],
    features: {
      cars: true,
      motos: false,
      audio: true,
      food: true,
    },
    ticketBatches: [
      {
        id: 'batch-4',
        name: 'Pista Família',
        description: 'Entrada individual para toda a área social e estandes.',
        price: 35.0,
        totalQuantity: 500,
        soldQuantity: 340,
        available: true,
        batchNumber: 1,
      },
      {
        id: 'batch-5',
        name: 'Camarote Prime',
        description: 'Área com mesas, garçons e visão frontal do palco principal.',
        price: 75.0,
        totalQuantity: 200,
        soldQuantity: 180,
        available: true,
        batchNumber: 1,
      },
    ],
    latitude: -20.2582,
    longitude: -42.0336,
  },
  {
    id: 'evt-3',
    slug: 'mega-encontro',
    name: 'Mega Encontro',
    tagline: 'Caminhões customizados, carretas de som e supermáquinas',
    description: 'A maior concentração de gigantes do asfalto, carretas temáticas, caminhões rebaixados e som de alta potência de Minas Gerais.',
    date: '27 de Dezembro de 2025',
    dateBadge: '27 DEZ',
    time: 'Das 08:00 às 22:00',
    location: 'Parque de Exposições - Manhuaçu/MG',
    city: 'Manhuaçu',
    state: 'MG',
    status: 'EM_BREVE',
    bannerImage: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=800&q=80',
    ],
    features: {
      cars: true,
      motos: true,
      audio: true,
      food: true,
    },
    ticketBatches: [
      {
        id: 'batch-6',
        name: 'Pista Geral',
        description: 'Acesso à arena de caminhões e área de medição.',
        price: 50.0,
        totalQuantity: 700,
        soldQuantity: 290,
        available: true,
        batchNumber: 1,
      },
      {
        id: 'batch-7',
        name: 'Área Box VIP',
        description: 'Acesso aos boxes dos competidores e área de lounge.',
        price: 100.0,
        totalQuantity: 200,
        soldQuantity: 110,
        available: true,
        batchNumber: 1,
      },
    ],
    latitude: -20.2582,
    longitude: -42.0336,
  },
];

export const CURRENT_USER: UserProfile = {
  id: 'usr-deivid-01',
  name: 'Deivid Santos',
  email: 'deividbmx779@gmail.com',
  phone: '(33) 99876-5432',
  cpf: '123.456.789-00',
  city: 'Manhuaçu',
  state: 'MG',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
  role: 'SUPER_ADMIN',
  createdAt: '2025-01-10T14:00:00Z',
};

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    userId: 'usr-deivid-01',
    type: 'Carro',
    brand: 'Chevrolet',
    model: 'Classic',
    year: 2012,
    color: 'Prata',
    plate: 'PXC-2012',
    category: 'Rebaixado',
    description: 'Suspensão a ar montada pela PX Custom, rodas aro 17 tala 6, som interno com kit 2 vias.',
    photoUrl: 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'veh-2',
    userId: 'usr-deivid-01',
    type: 'Carro',
    brand: 'Volkswagen',
    model: 'Gol G5',
    year: 2010,
    color: 'Preto',
    plate: 'MGH-4490',
    category: 'Som Automotivo',
    description: 'Porta malas montado com 2 subwoofers de 15 polegadas e cornetas trio.',
    photoUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'tkt-001',
    code: 'PX-2025-ENC-74892',
    eventId: 'evt-1',
    eventName: 'Encontro PX Custom',
    eventDate: '15/11/2025',
    eventTime: '08:00 às 22:00',
    eventLocation: 'Parque de Exposições - Manhuaçu/MG',
    batchName: 'Pista',
    price: 40.0,
    buyerName: 'Deivid Santos',
    buyerEmail: 'deividbmx779@gmail.com',
    buyerCpf: '123.456.789-00',
    buyerPhone: '(33) 99876-5432',
    userId: 'usr-deivid-01',
    status: 'PAGO',
    paymentMethod: 'PIX',
    createdAt: '2025-11-10T12:30:00Z',
    qrPayload: 'PX-2025-ENC-74892|evt-1|usr-deivid-01|PAGO',
  },
  {
    id: 'tkt-002',
    code: 'PX-2025-FES-19842',
    eventId: 'evt-2',
    eventName: 'Festival da Família',
    eventDate: '12/12/2025',
    eventTime: '10:00 às 20:00',
    eventLocation: 'Parque de Exposições - Manhuaçu/MG',
    batchName: 'Camarote Prime',
    price: 75.0,
    buyerName: 'Deivid Santos',
    buyerEmail: 'deividbmx779@gmail.com',
    buyerCpf: '123.456.789-00',
    buyerPhone: '(33) 99876-5432',
    userId: 'usr-deivid-01',
    status: 'PAGO',
    paymentMethod: 'CARTAO',
    createdAt: '2025-11-12T16:15:00Z',
    qrPayload: 'PX-2025-FES-19842|evt-2|usr-deivid-01|PAGO',
  },
];

export const INITIAL_CHECKINS: CheckInLog[] = [
  {
    id: 'chk-1',
    ticketCode: 'PX-2025-ENC-90112',
    attendeeName: 'João Silva',
    batchName: 'Pista',
    eventName: 'Encontro PX Custom',
    timestamp: '15/11/2025 • 14:32',
    operatorName: 'Operador PX Portaria 1',
    status: 'CONFIRMADO',
  },
  {
    id: 'chk-2',
    ticketCode: 'PX-2025-ENC-38814',
    attendeeName: 'Lucas Ferreira',
    batchName: 'Camarote',
    eventName: 'Encontro PX Custom',
    timestamp: '15/11/2025 • 14:28',
    operatorName: 'Operador PX VIP',
    status: 'CONFIRMADO',
  },
  {
    id: 'chk-3',
    ticketCode: 'PX-2025-ENC-44109',
    attendeeName: 'Rafael Souza',
    batchName: 'VIP',
    eventName: 'Encontro PX Custom',
    timestamp: '15/11/2025 • 14:21',
    operatorName: 'Operador PX VIP',
    status: 'CONFIRMADO',
  },
  {
    id: 'chk-4',
    ticketCode: 'PX-2025-ENC-12003',
    attendeeName: 'Matheus Oliveira',
    batchName: 'Pista',
    eventName: 'Encontro PX Custom',
    timestamp: '15/11/2025 • 14:05',
    operatorName: 'Operador PX Portaria 2',
    status: 'CONFIRMADO',
  },
];

export const INITIAL_DASHBOARD_STATS: DashboardStats = {
  ticketsSold: 742,
  ticketsSoldGrowth: 12,
  ticketsAvailable: 258,
  checkinsCount: 531,
  checkinsGrowth: 8,
  totalRevenue: 29680.0,
  revenueGrowth: 15,
  salesByDay: [
    { date: '08/11', count: 42, revenue: 1680 },
    { date: '09/11', count: 68, revenue: 2720 },
    { date: '10/11', count: 110, revenue: 4400 },
    { date: '11/11', count: 95, revenue: 3800 },
    { date: '12/11', count: 140, revenue: 5600 },
    { date: '13/11', count: 125, revenue: 5000 },
    { date: '14/11', count: 155, revenue: 6200 },
    { date: '15/11', count: 172, revenue: 6880 },
  ],
  salesByBatch: [
    { name: 'Pista', percentage: 52, count: 386 },
    { name: 'Camarote', percentage: 28, count: 208 },
    { name: 'VIP', percentage: 20, count: 148 },
  ],
  revenueByDay: [
    { date: '08/11', amount: 3200 },
    { date: '09/11', amount: 5400 },
    { date: '10/11', amount: 8900 },
    { date: '11/11', amount: 12400 },
    { date: '12/11', amount: 16800 },
    { date: '13/11', amount: 21500 },
    { date: '14/11', amount: 25900 },
    { date: '15/11', amount: 29680 },
  ],
  paymentMethods: [
    { method: 'PIX', percentage: 62, count: 460 },
    { method: 'Cartão de Crédito', percentage: 28, count: 208 },
    { method: 'Boleto', percentage: 6, count: 44 },
    { method: 'Outros', percentage: 4, count: 30 },
  ],
  recentCheckins: INITIAL_CHECKINS,
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Pagamento aprovado',
    message: 'Seu ingresso para o Encontro PX Custom foi confirmado com sucesso.',
    type: 'SUCCESS',
    read: false,
    createdAt: 'Hoje às 12:30',
  },
  {
    id: 'notif-2',
    title: 'Seu ingresso está disponível',
    message: 'Acesse "Meus Ingressos" para visualizar seu QR Code digital de entrada.',
    type: 'INFO',
    read: false,
    createdAt: 'Hoje às 12:31',
  },
  {
    id: 'notif-3',
    title: 'Seu evento acontece em breve',
    message: 'O Encontro PX Custom no Parque de Exposições começa às 08:00.',
    type: 'INFO',
    read: false,
    createdAt: 'Ontem às 18:00',
  },
  {
    id: 'notif-4',
    title: 'Regras de Som Automotivo',
    message: 'Confira as regras e faixas de decibéis permitidas na arena principal.',
    type: 'INFO',
    read: true,
    createdAt: '01/11/2025',
  },
];

export const INITIAL_MERCADO_PAGO_CONFIG: MercadoPagoConfig = {
  environment: 'production',
  accessToken: 'APP_USR-7894120894578123-111520-a8f89e1a2fbc789e90214a678b-87421190',
  publicKey: 'APP_USR-8b2938a1-c891-4cf1-87a2-990a12e8412b',
  webhookSecret: 'whsec_908a8f8e12903847bca8817293a0bcf8',
  pixEnabled: true,
  creditCardEnabled: true,
  boletoEnabled: true,
  connected: true,
  lastTestedAt: 'Hoje às 14:10',
};
